pipeline {
    agent {
        label 'ubuntu'
    }

    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/Rayman1993/tms-git/tree/homework/Buchinsky/hw32_jenkins2/simple-dockerfile-example', branch: 'homework'
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.build('rayman1993/hello')
                    // безопасно храним токен для докерхаба
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub') {
                        docker.image('rayman1993/hello').push('latest')
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker_hub') {
                        docker.image('rayman1993/hello').run("-p 8080:8080")
                    }
                }
            }
        }
    }
}
